### ISSUE TITLE
A quick question on dissector

### ISSUE THREAD

**Issue by user1020** [kunklejr/node-pcap-parser#4]
This module looks interesting.

Wonder if it can call the dissectors in wireshark dynamically and get the dissected packets (ip layer, tcp/udp layer,  http... layer) in a JSON format?

**Comment by kunklejr** [comment]
You could build such a capability using this module, but incorporating the functionality is beyond the module's intended scope.

**Comment by joeferner** [comment]
You may want to checkout
- https://github.com/joeferner/node-shark
- https://github.com/joeferner/node-tshark (lighter weight version of node-shark)

I haven't really kept up with them but they may be a starting point.

**Comment by user1020** [comment]
Thanks Jeff and Joe. Will check them out.
